apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::851663248626:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-125XKM6JBD7VQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam:::851663248626:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-16T19:33:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1581"
  uid: dcf16556-077c-45bb-9ef2-7b1282337413
